# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeparateCollectionAlphaGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeparateCollectionAlphaGo
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'Alamofire', '~> 5.4'
pod 'NMapsMap'
 pod 'SWXMLHash'
end
